import Navigation from '@/components/Navigation'
import './globals.css'
// eslint-disable-next-line camelcase
import { Comic_Neue } from 'next/font/google'

const comicNeue = Comic_Neue({ subsets: ['latin'], weight: '700' })

export const metadata = {
  title: 'Next 13 App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className='mx-52'>
        <div className={comicNeue.className}>
        <Navigation />
        {children }
        </div>
      </body>
    </html>
  )
}
